-- MySQL Script generated by MySQL Workbench
-- Sat Jun 10 23:31:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quanlysitedaugia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quanlysitedaugia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quanlysitedaugia` DEFAULT CHARACTER SET utf8 ;
USE `quanlysitedaugia` ;

-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`USER` (
  `idUSER` INT NOT NULL,
  `tendangnhap` VARCHAR(30) NULL,
  `matkhau` VARCHAR(30) NULL,
  `hoten` VARCHAR(100) NULL,
  `gioitinh` VARCHAR(5) NULL,
  `ngaysinh` DATETIME NULL,
  `sodienthoai` VARCHAR(20) NULL,
  `diachi` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`idUSER`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`SANPHAMYEUTHICH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`SANPHAMYEUTHICH` (
  `idSANPHAMYEUTHICH` INT NOT NULL,
  `USER_idUSER` INT NOT NULL,
  `idsanpham` INT NULL,
  PRIMARY KEY (`idSANPHAMYEUTHICH`, `USER_idUSER`),
  INDEX `fk_SANPHAMYEUTHICH_USER_idx` (`USER_idUSER` ASC),
  CONSTRAINT `fk_SANPHAMYEUTHICH_USER`
    FOREIGN KEY (`USER_idUSER`)
    REFERENCES `quanlysitedaugia`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`COMMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`COMMENT` (
  `idCOMMENT` INT NOT NULL,
  `USER_idUSER(nguoicomment)` INT NOT NULL,
  `noidungcomment` VARCHAR(300) NULL,
  `idnguoiduocomment` INT NULL,
  PRIMARY KEY (`idCOMMENT`, `USER_idUSER(nguoicomment)`),
  INDEX `fk_COMMENT_USER1_idx` (`USER_idUSER(nguoicomment)` ASC),
  CONSTRAINT `fk_COMMENT_USER1`
    FOREIGN KEY (`USER_idUSER(nguoicomment)`)
    REFERENCES `quanlysitedaugia`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`SANPHAMDAUGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`SANPHAMDAUGIA` (
  `idSANPHAMDAUGIA` INT NOT NULL,
  `USER_idUSER` INT NOT NULL,
  `idsanpham` INT NULL,
  PRIMARY KEY (`idSANPHAMDAUGIA`, `USER_idUSER`),
  INDEX `fk_SANPHAMDAUGIA_USER1_idx` (`USER_idUSER` ASC),
  CONSTRAINT `fk_SANPHAMDAUGIA_USER1`
    FOREIGN KEY (`USER_idUSER`)
    REFERENCES `quanlysitedaugia`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`SANPHAMDAUGIATHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`SANPHAMDAUGIATHANG` (
  `idSANPHAMDAUGIATHANG` INT NOT NULL,
  `USER_idUSER` INT NOT NULL,
  `idsanpham` INT NULL,
  PRIMARY KEY (`idSANPHAMDAUGIATHANG`, `USER_idUSER`),
  INDEX `fk_SANPHAMDAUGIATHANG_USER1_idx` (`USER_idUSER` ASC),
  CONSTRAINT `fk_SANPHAMDAUGIATHANG_USER1`
    FOREIGN KEY (`USER_idUSER`)
    REFERENCES `quanlysitedaugia`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`SANPHAMCONHAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`SANPHAMCONHAN` (
  `idSANPHAMCONHAN` INT NOT NULL,
  `USER_idUSER` INT NOT NULL,
  `idsanpham` INT NULL,
  PRIMARY KEY (`idSANPHAMCONHAN`, `USER_idUSER`),
  INDEX `fk_SANPHAMCONHAN_USER1_idx` (`USER_idUSER` ASC),
  CONSTRAINT `fk_SANPHAMCONHAN_USER1`
    FOREIGN KEY (`USER_idUSER`)
    REFERENCES `quanlysitedaugia`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`SANPHAMCONGUOIMUA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`SANPHAMCONGUOIMUA` (
  `idSANPHAMCONGUOIMUA` INT NOT NULL,
  `USER_idUSER` INT NOT NULL,
  `idsanpham` INT NULL,
  PRIMARY KEY (`idSANPHAMCONGUOIMUA`, `USER_idUSER`),
  INDEX `fk_SANPHAMCONGUOIMUA_USER1_idx` (`USER_idUSER` ASC),
  CONSTRAINT `fk_SANPHAMCONGUOIMUA_USER1`
    FOREIGN KEY (`USER_idUSER`)
    REFERENCES `quanlysitedaugia`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`LOAISANPHAM1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`LOAISANPHAM1` (
  `idLOAISANPHAM1` INT NOT NULL,
  `tensanpham` VARCHAR(50) NULL,
  PRIMARY KEY (`idLOAISANPHAM1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`LOAISANPHAM2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`LOAISANPHAM2` (
  `idLOAISANPHAM2` INT NOT NULL,
  `tensanpham` VARCHAR(50) NULL,
  `LOAISANPHAM1_idLOAISANPHAM1` INT NOT NULL,
  PRIMARY KEY (`idLOAISANPHAM2`, `LOAISANPHAM1_idLOAISANPHAM1`),
  INDEX `fk_LOAISANPHAM2_LOAISANPHAM11_idx` (`LOAISANPHAM1_idLOAISANPHAM1` ASC),
  CONSTRAINT `fk_LOAISANPHAM2_LOAISANPHAM11`
    FOREIGN KEY (`LOAISANPHAM1_idLOAISANPHAM1`)
    REFERENCES `quanlysitedaugia`.`LOAISANPHAM1` (`idLOAISANPHAM1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`LOAISANPHAM3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`LOAISANPHAM3` (
  `idLOAISP3` INT NOT NULL,
  `tensanpham` VARCHAR(50) NULL,
  `LOAISANPHAM2_idLOAISANPHAM2` INT NOT NULL,
  PRIMARY KEY (`idLOAISP3`, `LOAISANPHAM2_idLOAISANPHAM2`),
  INDEX `fk_LOAISANPHAM3_LOAISANPHAM21_idx` (`LOAISANPHAM2_idLOAISANPHAM2` ASC),
  CONSTRAINT `fk_LOAISANPHAM3_LOAISANPHAM21`
    FOREIGN KEY (`LOAISANPHAM2_idLOAISANPHAM2`)
    REFERENCES `quanlysitedaugia`.`LOAISANPHAM2` (`idLOAISANPHAM2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`SANPHAM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`SANPHAM` (
  `idSANPHAM` INT NOT NULL,
  `LOAISANPHAM3_idLOAISP3` INT NOT NULL,
  `tensanpham` VARCHAR(50) NULL,
  `motasanphamngangon` VARCHAR(100) NULL,
  `motasanphamfull` VARCHAR(500) NULL,
  `gia` FLOAT NULL,
  `hinhanh` BLOB NULL,
  `giamualien` FLOAT NULL,
  `USER_idUSER(idnguoiban)` INT NOT NULL,
  `thoigianbatdauban` DATETIME NULL,
  `thoigiankethuc` DATETIME NULL,
  `USER_idUSER1(idnguoithang)` INT NOT NULL,
  `buocgia` FLOAT NULL,
  `LOAISANPHAM3_LOAISANPHAM2_idLOAISANPHAM2` INT NOT NULL,
  PRIMARY KEY (`idSANPHAM`, `LOAISANPHAM3_idLOAISP3`, `USER_idUSER(idnguoiban)`, `USER_idUSER1(idnguoithang)`, `LOAISANPHAM3_LOAISANPHAM2_idLOAISANPHAM2`),
  INDEX `fk_SANPHAM_USER1_idx` (`USER_idUSER(idnguoiban)` ASC),
  INDEX `fk_SANPHAM_USER2_idx` (`USER_idUSER1(idnguoithang)` ASC),
  INDEX `fk_SANPHAM_LOAISANPHAM31_idx` (`LOAISANPHAM3_idLOAISP3` ASC, `LOAISANPHAM3_LOAISANPHAM2_idLOAISANPHAM2` ASC),
  CONSTRAINT `fk_SANPHAM_USER1`
    FOREIGN KEY (`USER_idUSER(idnguoiban)`)
    REFERENCES `quanlysitedaugia`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SANPHAM_USER2`
    FOREIGN KEY (`USER_idUSER1(idnguoithang)`)
    REFERENCES `quanlysitedaugia`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SANPHAM_LOAISANPHAM31`
    FOREIGN KEY (`LOAISANPHAM3_idLOAISP3` , `LOAISANPHAM3_LOAISANPHAM2_idLOAISANPHAM2`)
    REFERENCES `quanlysitedaugia`.`LOAISANPHAM3` (`idLOAISP3` , `LOAISANPHAM2_idLOAISANPHAM2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`CHITIETDAUGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`CHITIETDAUGIA` (
  `idCHITIETDAUGIA` INT NOT NULL,
  `SANPHAM_idSANPHAM(idsanphamdaugia)` INT NOT NULL,
  `USER_idUSER(idnguoidaugia)` INT NOT NULL,
  `sotien` FLOAT NULL,
  `thoigiandaugia` DATETIME NULL,
  PRIMARY KEY (`idCHITIETDAUGIA`, `SANPHAM_idSANPHAM(idsanphamdaugia)`, `USER_idUSER(idnguoidaugia)`),
  INDEX `fk_CHITIETDAUGIA_USER1_idx` (`USER_idUSER(idnguoidaugia)` ASC),
  INDEX `fk_CHITIETDAUGIA_SANPHAM1_idx` (`SANPHAM_idSANPHAM(idsanphamdaugia)` ASC),
  CONSTRAINT `fk_CHITIETDAUGIA_USER1`
    FOREIGN KEY (`USER_idUSER(idnguoidaugia)`)
    REFERENCES `quanlysitedaugia`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETDAUGIA_SANPHAM1`
    FOREIGN KEY (`SANPHAM_idSANPHAM(idsanphamdaugia)`)
    REFERENCES `quanlysitedaugia`.`SANPHAM` (`idSANPHAM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`KHACHHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`KHACHHANG` (
  `idKHACHHANG` INT NOT NULL,
  `hoten` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idKHACHHANG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quanlysitedaugia`.`DONHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysitedaugia`.`DONHANG` (
  `idDONHANG` INT NOT NULL,
  `ngaytratien` DATETIME NULL,
  `kieuthanhtoan` VARCHAR(45) NULL,
  `KHACHHANG_idKHACHHANG` INT NOT NULL,
  PRIMARY KEY (`idDONHANG`, `KHACHHANG_idKHACHHANG`),
  INDEX `fk_DONHANG_KHACHHANG1_idx` (`KHACHHANG_idKHACHHANG` ASC),
  CONSTRAINT `fk_DONHANG_KHACHHANG1`
    FOREIGN KEY (`KHACHHANG_idKHACHHANG`)
    REFERENCES `quanlysitedaugia`.`KHACHHANG` (`idKHACHHANG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
